'use client'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import queryClient, { QueryClientProvider } from '@/app/config/react-query'
import AuthProvider from './context/auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
            <AuthProvider>
              {children}
            </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  )
}
